### ISSUE TITLE
Localisation of NSAttributed String.

### ISSUE THREAD

**Issue by saikumar-osv** [Abedalkareem/LanguageManager-iOS#52]
Im having attributed UILables and UIButtons and from swizzledAwakeFromNib I can see only String are getting localised not NSAtrributedStrings.

**Comment by Abedalkareem** [comment]
Hi Saikumar,
The NSAtrributedStrings is hard to localize in this way because attributed strings have multiple properties and ranges and it will be changed when you change the language, also, it's not supported by Apple for now*.
So what I'm suggesting is to localize the text first in the code then apply the attribute to it.

Thank you!

*
https://developer.apple.com/forums/thread/661903
